FROM eclipse-temurin:8-jdk

ENV HADOOP_VERSION=3.3.6
ENV HIVE_VERSION=3.1.3

RUN apt-get update && \
    apt-get install -y \
        wget \
        curl \
        procps \
        netcat-openbsd \
        tar && \
    rm -rf /var/lib/apt/lists/*

# -------------------------
# Install Hadoop
# -------------------------
RUN wget https://downloads.apache.org/hadoop/common/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz && \
    tar -xzf hadoop-${HADOOP_VERSION}.tar.gz && \
    mv hadoop-${HADOOP_VERSION} /opt/hadoop && \
    rm hadoop-${HADOOP_VERSION}.tar.gz

# -------------------------
# Install Hive
# -------------------------
RUN wget https://archive.apache.org/dist/hive/hive-${HIVE_VERSION}/apache-hive-${HIVE_VERSION}-bin.tar.gz && \
    tar -xzf apache-hive-${HIVE_VERSION}-bin.tar.gz && \
    mv apache-hive-${HIVE_VERSION}-bin /opt/hive && \
    rm apache-hive-${HIVE_VERSION}-bin.tar.gz

ENV HADOOP_HOME=/opt/hadoop
ENV HADOOP_PREFIX=/opt/hadoop
ENV HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop

ENV HIVE_HOME=/opt/hive

ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$HIVE_HOME/bin

COPY drivers/postgresql.jar /opt/hive/lib/

COPY hadoop-conf/core-site.xml /opt/hadoop/etc/hadoop/
COPY hadoop-conf/hdfs-site.xml /opt/hadoop/etc/hadoop/
COPY hadoop-conf/core-site.xml /opt/hive/conf/
COPY hadoop-conf/hdfs-site.xml /opt/hive/conf/
COPY hadoop-conf/hive-site.xml /opt/hive/conf/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]