version: '3'

services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode

    ports:
      - "9870:9870"
      - "9000:9000"

    volumes:
      - namenode-data:/hadoop/dfs/name 
      - ../data:/data 
 
    environment:
      CLUSTER_NAME: stock-cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000 

    networks:
      - hadoop-network   

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode

    depends_on:
      - namenode 

    volumes:
      - datanode-data:/hadoop/dfs/data  

    environment:
      SERVICE_PRECONDITION: "namenode:9870"   
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: 1

    networks:
      - hadoop-network

  spark:
    image: apache/spark:3.5.7-python3
    container_name: spark
    hostname: spark

    command: tail -f /dev/null

    depends_on:
      - namenode
      - datanode

    volumes:
      - ../:/app
      - ./hadoop-conf:/opt/spark/conf

    environment:
      HADOOP_CONF_DIR: /opt/spark/conf  

    working_dir: /app

    tty: true
    stdin_open: true

    networks:
      - hadoop-network          

volumes:
  namenode-data:
  datanode-data:    

networks:
  hadoop-network:         
